[2025-07-21 07:36:47 +0000] [8701] [INFO] Starting gunicorn 23.0.0
[2025-07-21 07:36:47 +0000] [8701] [INFO] Listening at: unix:/root/jetlux/jetski/jetlux.sock (8701)
[2025-07-21 07:36:47 +0000] [8701] [INFO] Using worker: sync
[2025-07-21 07:36:47 +0000] [8702] [INFO] Booting worker with pid: 8702
[2025-07-21 07:36:47 +0000] [8703] [INFO] Booting worker with pid: 8703
[2025-07-21 07:36:47 +0000] [8704] [INFO] Booting worker with pid: 8704
[2025-07-21 07:49:51 +0000] [8701] [INFO] Handling signal: term
[2025-07-21 07:49:51 +0000] [8702] [INFO] Worker exiting (pid: 8702)
[2025-07-21 07:49:51 +0000] [8703] [INFO] Worker exiting (pid: 8703)
[2025-07-21 07:49:51 +0000] [8704] [INFO] Worker exiting (pid: 8704)
[2025-07-21 07:49:51 +0000] [8701] [ERROR] Worker (pid:8702) was sent SIGTERM!
[2025-07-21 07:49:51 +0000] [8701] [ERROR] Worker (pid:8703) was sent SIGTERM!
[2025-07-21 07:49:51 +0000] [8701] [INFO] Shutting down: Master
[2025-07-21 07:50:01 +0000] [8945] [INFO] Starting gunicorn 23.0.0
[2025-07-21 07:50:01 +0000] [8945] [INFO] Listening at: unix:/root/jetlux/jetski/jetlux.sock (8945)
[2025-07-21 07:50:01 +0000] [8945] [INFO] Using worker: sync
[2025-07-21 07:50:01 +0000] [8946] [INFO] Booting worker with pid: 8946
[2025-07-21 07:50:01 +0000] [8947] [INFO] Booting worker with pid: 8947
[2025-07-21 07:50:01 +0000] [8948] [INFO] Booting worker with pid: 8948
Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost'. You may need to add 'localhost' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/root/jetlux/jetski/env/lib/python3.12/site-packages/django/http/request.py", line 202, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '134.199.192.37'. You may need to add '134.199.192.37' to ALLOWED_HOSTS.
